# Generated by Django 2.2.16 on 2022-02-15 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='following',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='follow',
            name='user',
            field=models.CharField(max_length=200),
        ),
    ]
